development:
    adapter: mysql
    database: niche_development
    username: root
    password: pop123
    host: localhost	
test:
    adapter: mysql
    database: niche_test
    username: root
    password: pop123
    host: localhost
production:
    adapter: mysql
    database: niche_production
    username: root
    password: pop123
    host: localhost