development:
    adapter: mysql2
    database: ideagen_development
    username: root
    password: pop123
    host: localhost	
test:
    adapter: mysql2
    database: ideagen_test
    username: root
    password: pop123
    host: localhost
production:
  adapter: mysql2
  encoding: utf8
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  pool: 30
  timeout: 30000
  checkout_timeout: 30000
  host: <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>